---
title: Tomasz Werner
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: posts
    credits: 
    roles: 
    video-url: 
    thumbnail-image: 
- scope:
    path: ''
    type: pages
  values:
    layout: category
    categories: 
    social-image: 
    title: 
keywords: Video, Producer
author: Tomasz Werner
email: tomaszpwerner@gmail.com
description: Tomasz Werner
markdown: kramdown
theme: minima
